[pytest]

addopts = 
    -v
    --alluredir=reports/allure-results

testpaths = testcase

python_files = test_*.py
python_functions = test_*

markers =
    smoke: quick critical tests
    regression: full suite
    sanity: basic functionality