class Config:
    BASE_URL = "https://demoqa.com"
    LOGIN_URL = f"{BASE_URL}/login"
    TEXTBOX_URL = f"{BASE_URL}/text-box"
    CHECKBOX_URL = f"{BASE_URL}/checkbox"
    RADIO_URL = f"{BASE_URL}/radio-button"
    BUTTONS_URL = f"{BASE_URL}/buttons"
    UPLOAD_DOWNLOAD_URL = f"{BASE_URL}/upload-download"
    DROPPABLE_URL = "https://jqueryui.com/droppable/"
    DROPDOWN_URL = f"{BASE_URL}/select-menu"